
spring.datasource.driverClassName=org.postgresql.Driver
server:
  port: 9090
# spring:
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     type: com.alibaba.druid.pool.DruidDataSource
#     url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
#     username: root
#     password: zyy010330

  web:
    resources:
      static-locations: classpath:/static/

logging:
  config: classpath:logback-spring.xml
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




